apiVersion: apps/v1
kind: Deployment
metadata:
  name: jeeva-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jeeva-app
  template:
    metadata:
      labels:
        app: jeeva-app
    spec:
      containers:
        - name: jeeva-app
          image: appi12/html01:2
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: jeeva-app-service
spec:
  selector:
    app: jeeva-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
