apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-my
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: html-my
  template:
    metadata:
      labels:
        app: html-my
    spec:
      containers:
      - name: html-container
        image: appi12/html01:${BUILD_NUMBER}
        ports:
        - containerPort: 80
