apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-app-deployment
  labels:
    agent: kubernetes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: html-app
  template:
    metadata:
      labels:
        app: html-app
        agent: kubernetes  # Adding agent label here
    spec:
      containers:
        - name: html-app
          image: appi12/html01:2
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: html-app-service
  labels:
    agent: kubernetes  # Adding agent label here
spec:
  selector:
    app: html-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
